<?php
/**
 * User: tangtaiming
 * Date: 2020/4/10
 * Time: 23:14
 */

namespace app\admin\controller;

use app\admin\service\OvertimeService;
use think\App;
use think\Controller;
use think\Request;

/**
 * 加班打卡
 * Class OvertimeController
 * @package app\index\controller
 */
class OvertimeController extends Controller
{

    private $overtimeService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->overtimeService = new OvertimeService();
    }

    /**
     * 显示资源列表
     *
     * @param Request $request
     * @return \think\Response
     */
    public function index(Request $request) {
//        echo $this->overtimeService->overDatetime();
        $data = $this->overtimeService->index($request);
//        echo $overDatetimeList;
        return $this->fetch('index', $data);
    }

    /**
     * 显示创建打卡加班表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        $data = $this->overtimeService->overDateTimeCreateData();
        return $this->fetch('create-overtime', $data);
    }

    /**
     * 显示编辑打卡加班表单页
     * @return mixed
     */
    public function edit($id)
    {
        $data = $this->overtimeService->overDateTimeEditData($id);
        return $this->fetch('edit-overtime', $data);
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $overtimeService = new OvertimeService();
        return $overtimeService->save($request);
    }

    /**
     * 批量删除
     * @param Request $request
     * @return mixed
     */
    public function batchDelete(Request $request) {
        return $this->overtimeService->batchDelete($request);
    }

    /**
     * 删除
     * @param Request $request
     * @return mixed
     */
    public function delete(Request $request) {
        return $this->overtimeService->delete($request);
    }

    /**
     * 高级搜索
     * @param Request $request
     * @return mixed
     */
    public function search(Request $request) {
        if ($request->method() == 'POST') {
            $data = $this->overtimeService->index($request);
            return $this->fetch('index', $data);
        } else {
            return $this->fetch('search-overtime');
        }
    }

}