<?php
/**
 * User: tangtaiming
 * Date: 2020/4/5
 * Time: 10:44
 */

namespace app\api\model;


use think\Db;
use think\Model;

/**
 * 豆瓣电影
 * Class Movie
 * @package app\api\model
 */
class DoubanMovie extends Model
{

    private $db;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->db = Db::name('douban_movie');
    }

    public function findMovieList() {
        return $this->db->select();
    }

}