<?php


namespace app\api\model;

use think\Db;
use think\Model;

/**
 * 学习卡片
 * Class LearnCard
 * @package app\api\model
 */
class Learncard extends Model
{

    private $db;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->db = Db::name('learncard');
    }

}